#coding=utf-8
from django import forms

class SearchForm(forms.Form):

    DYS388 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS388')
    DYS19 = forms.IntegerField(required=False, min_value=0, max_value=99, label=ur'DYS19/394')
    DYS389I = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS389I')
    DYS389II = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS389II')
    DYS390 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS390')
    DYS391 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS391')
    DYS392 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS392')
    DYS393 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS393')
    DYS425 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS425')
    DYS426 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS426')
    DYS434 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS434')
    DYS435 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS435')
    DYS436 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS436')
    DYS437 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS437')
    DYS438 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS438')
    DYS439 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS439')
    DYS385a = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS385a')
    DYS385b = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS385b')
    DYSA1_2 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYSA7.2')
    YGATAH4 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'Y GATE H4')
    DYS448 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS448')
    DYS456 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS456')
    DYS458 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS458')
    DYS635 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS635')
    YCAIIa = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'YCAIIa')
    YCAIIb = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'YCAIIb')
    DYS594 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS594')
    DYS596 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS596')
    YPENTA1 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'Y PENTA 1')
    YPENTA2 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'Y PENTA 2')
    DYS643 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS643')
    DYS645 = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYS645')
    DYF411S1a = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYF411S1a')
    DYF411S1b = forms.IntegerField(required=False, min_value=0, max_value=99, label=u'DYF411S1b')
